# Generated by Django 6.0 on 2026-05-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stockadjustmentreason'),
        ('gifts', '0002_gift_manufacturer_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='reason',
            field=models.ForeignKey(blank=True, help_text='Reason for transaction (from standardized list)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stockadjustmentreason'),
        ),
    ]
