# Generated by Django 6.0 on 2025-12-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Gift Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to="gift_images/"),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("qty_stock", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("material", models.CharField(blank=True, max_length=200)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hs_code", models.CharField(blank=True, max_length=20)),
                ("country_of_origin", models.CharField(blank=True, max_length=100)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("supplier_email", models.EmailField(blank=True, max_length=254)),
                ("supplier_address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("minimum_stock_level", models.IntegerField(blank=True, default=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.giftcategory",
                    ),
                ),
            ],
        ),
    ]
