# Generated by Django 6.0 on 2026-01-09 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("take", "Take"), ("return", "Return")], max_length=10
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("event", "Event"),
                            ("office_use", "Office Use"),
                            ("external_gift", "External Gift (Visitors/Meetings)"),
                            ("new_employee", "New Employee Welcome"),
                            ("damaged", "Damaged/Defective"),
                            ("sample", "Sample"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stock_before", models.IntegerField()),
                ("stock_after", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.gift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
