# Generated by Django 6.0 on 2026-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_inventorytransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparelSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_value",
                    models.CharField(
                        help_text="Size identifier (e.g., 'M', 'XL', '42')",
                        max_length=10,
                    ),
                ),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing"),
                            ("footwear", "Footwear"),
                            ("accessory", "Accessories"),
                        ],
                        help_text="Category of size: clothing or footwear",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for dropdown display (smaller numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Apparel Size",
                "verbose_name_plural": "Apparel Sizes",
                "ordering": ["size_type", "display_order"],
                "unique_together": {("size_value", "size_type")},
            },
        ),
    ]
