# Generated by Django 6.0 on 2026-01-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_apparelsize"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparelColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_name",
                    models.CharField(
                        help_text="Standardized color name (e.g., 'Navy Blue', 'Black')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "hex_code",
                    models.CharField(
                        blank=True,
                        help_text="Optional hex color code for visual display (e.g., '#001f3f')",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Apparel Color",
                "verbose_name_plural": "Apparel Colors",
                "ordering": ["color_name"],
            },
        ),
    ]
