# Generated by Django 6.0 on 2026-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_apparelcolor"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakeReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_name",
                    models.CharField(
                        help_text="Descriptive reason for taking inventory (e.g., 'World Cup 2026 Gift')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("gifts", "Gifts Only"),
                            ("apparel", "Apparel Only"),
                            ("both", "Both Inventories"),
                        ],
                        default="both",
                        help_text="Which inventory system(s) can use this reason",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Take Reason",
                "verbose_name_plural": "Take Reasons",
                "ordering": ["reason_name"],
            },
        ),
    ]
