# Generated by Django 6.0 on 2026-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_takereason"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Apparel Category",
                "verbose_name_plural": "Apparel Categories",
                "ordering": ["name"],
            },
        ),
    ]
