# Generated by Django 6.0 on 2026-01-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_apparelcategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparelProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Full product name (e.g., '361° Staff Polo Blue')",
                        max_length=200,
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        blank=True,
                        help_text="361° product code (e.g., 'ZW1050601-2')",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Men"),
                            ("W", "Women"),
                            ("U", "Unisex"),
                            ("Y", "Youth"),
                        ],
                        default="U",
                        help_text="Target gender for this product",
                        max_length=1,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="Fabric composition (e.g., '100% Polyester')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed product description"
                    ),
                ),
                (
                    "hs_code",
                    models.CharField(
                        blank=True,
                        help_text="Harmonized System code for customs",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price per unit (same for all sizes of this product)",
                        max_digits=10,
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, help_text="Manufacturing country", max_length=100
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        help_text="Product photo for visual identification",
                        null=True,
                        upload_to="apparel_images/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for staff reference"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category for organization and filtering",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="api.apparelcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apparel_products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apparel_products_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Apparel Product",
                "verbose_name_plural": "Apparel Products",
                "ordering": ["product_name"],
            },
        ),
    ]
