# Generated by Django 6.0 on 2026-01-19 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_apparelproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparelVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_stock",
                    models.IntegerField(
                        default=0,
                        help_text="Current quantity in stock for this specific size/color",
                    ),
                ),
                (
                    "minimum_stock_level",
                    models.IntegerField(
                        default=5, help_text="Alert threshold for low stock warnings"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in grams (optional, for shipping calculations)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Full SKU from 361° if provided",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        help_text="Standardized color from predefined list",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.apparelcolor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apparel_variants_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Base product this variant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="api.apparelproduct",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        help_text="Standardized size from predefined list",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.apparelsize",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apparel_variants_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Apparel Variant",
                "verbose_name_plural": "Apparel Variants",
                "ordering": ["product", "size__display_order"],
                "unique_together": {("product", "size", "color")},
            },
        ),
    ]
