# Generated by Django 6.0 on 2026-01-19 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_apparelvariant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparelTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("take", "Take"), ("return", "Return")],
                        help_text="Whether items were taken out or returned to stock",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Number of items taken or returned"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context or details about this transaction",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this transaction occurred"
                    ),
                ),
                (
                    "stock_before",
                    models.IntegerField(
                        help_text="Stock quantity before this transaction"
                    ),
                ),
                (
                    "stock_after",
                    models.IntegerField(
                        help_text="Stock quantity after this transaction"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who performed this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reason for transaction (from standardized list)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.takereason",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Specific size/color variant that was taken or returned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.apparelvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apparel Transaction",
                "verbose_name_plural": "Apparel Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
