# Generated by Django 6.0 on 2026-01-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_appareltransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="reason_new",
            field=models.ForeignKey(
                blank=True,
                help_text="New dynamic reason (migrating from hardcoded choices)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.takereason",
            ),
        ),
    ]
