# Generated by Django 6.0 on 2026-01-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_migrate_transaction_reasons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorytransaction",
            name="reason",
        ),
    ]
