# Generated by Django 6.0 on 2026-01-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_inventorytransaction_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorytransaction",
            name="reason_new",
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="reason",
            field=models.ForeignKey(
                blank=True,
                help_text="Reason for transaction (from standardized list)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.takereason",
            ),
        ),
    ]
