# Generated by Django 6.0 on 2026-01-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_rename_reason_new_to_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparelproduct",
            name="primary_color",
            field=models.ForeignKey(
                blank=True,
                help_text="Main color of this product (determines badge background)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_of_this_color",
                to="api.apparelcolor",
            ),
        ),
    ]
