# Generated by Django 6.0 on 2026-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_apparelproduct_primary_color"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apparelvariant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="apparelvariant",
            name="gender",
            field=models.CharField(
                choices=[("U", "Unisex"), ("M", "Men"), ("W", "Women"), ("Y", "Youth")],
                default="U",
                help_text="Gender fit for this specific variant (Women's M vs Men's M)",
                max_length=1,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apparelvariant",
            unique_together={("product", "size", "color", "gender")},
        ),
    ]
