# Generated by Django 6.0 on 2026-01-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_apparelvariant_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apparelproduct",
            name="gender",
        ),
    ]
