# Generated by Django 6.0 on 2026-07-08 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_stockadjustmentreason_applies_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Miscellaneous Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MiscellaneousItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='miscellaneous_images/')),
                ('item_name', models.CharField(max_length=200)),
                ('qty_stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=20)),
                ('merchant_product_id', models.CharField(blank=True, help_text='Your unique product code / SKU for customs declarations', max_length=100)),
                ('manufacturer_product_id', models.CharField(blank=True, help_text="Supplier's non-standardised product code", max_length=100)),
                ('standardised_product_id', models.CharField(blank=True, help_text='Standardised code if exists: GTIN, EAN, ISBN. Enter NO if not applicable.', max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('supplier_phone', models.CharField(blank=True, max_length=50)),
                ('supplier_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miscellaneous.miscellaneouscategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miscellaneous_items_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miscellaneous_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('take', 'Take'), ('return', 'Return')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='miscellaneous.miscellaneousitem')),
                ('reason', models.ForeignKey(blank=True, help_text='Reason for transaction (from standardized list)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stockadjustmentreason')),
            ],
            options={
                'verbose_name': 'Miscellaneous Transaction',
                'verbose_name_plural': 'Miscellaneous Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
