# Generated by Django 6.0 on 2026-04-09 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApparelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apparel Category',
                'verbose_name_plural': 'Apparel Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApparelColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text="Standardized color name (e.g., 'Navy Blue', 'Black')", max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text="Optional hex color code for visual display (e.g., '#001f3f')", max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apparel Color',
                'verbose_name_plural': 'Apparel Colors',
                'ordering': ['color_name'],
            },
        ),
        migrations.CreateModel(
            name='ApparelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text="Full product name (e.g., '361° Staff Polo Blue')", max_length=200)),
                ('item_id', models.CharField(blank=True, help_text="361° product code (e.g., 'ZW1050601-2')", max_length=50)),
                ('material', models.CharField(blank=True, help_text="Fabric composition (e.g., '100% Polyester')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System code for customs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit (same for all sizes of this product)', max_digits=10)),
                ('country_of_origin', models.CharField(blank=True, help_text='Manufacturing country', max_length=100)),
                ('product_image', models.ImageField(blank=True, help_text='Product photo for visual identification', null=True, upload_to='apparel_images/')),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category for organization and filtering', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='apparel.apparelcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apparel_products_created', to=settings.AUTH_USER_MODEL)),
                ('primary_color', models.ForeignKey(blank=True, help_text='Main color of this product (determines badge background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_of_this_color', to='apparel.apparelcolor')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apparel_products_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apparel Product',
                'verbose_name_plural': 'Apparel Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='ApparelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.CharField(help_text="Size identifier (e.g., 'M', 'XL', '42')", max_length=10)),
                ('size_type', models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('accessory', 'Accessories')], help_text='Category of size: clothing or footwear', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order for dropdown display (smaller numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apparel Size',
                'verbose_name_plural': 'Apparel Sizes',
                'ordering': ['size_type', 'display_order'],
                'unique_together': {('size_value', 'size_type')},
            },
        ),
        migrations.CreateModel(
            name='ApparelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('U', 'Unisex'), ('M', 'Men'), ('W', 'Women'), ('Y', 'Youth')], default='U', help_text="Gender fit for this specific variant (Women's M vs Men's M)", max_length=1)),
                ('qty_stock', models.IntegerField(default=0, help_text='Current quantity in stock for this specific size/color')),
                ('minimum_stock_level', models.IntegerField(default=5, help_text='Alert threshold for low stock warnings')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams (optional, for shipping calculations)', max_digits=6, null=True)),
                ('sku', models.CharField(blank=True, help_text='Full SKU from 361° if provided', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(help_text='Standardized color from predefined list', on_delete=django.db.models.deletion.PROTECT, to='apparel.apparelcolor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apparel_variants_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Base product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='apparel.apparelproduct')),
                ('size', models.ForeignKey(help_text='Standardized size from predefined list', on_delete=django.db.models.deletion.PROTECT, to='apparel.apparelsize')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apparel_variants_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apparel Variant',
                'verbose_name_plural': 'Apparel Variants',
                'ordering': ['product', 'size__display_order'],
                'unique_together': {('product', 'size', 'color', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='ApparelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('take', 'Take'), ('return', 'Return')], help_text='Whether items were taken out or returned to stock', max_length=10)),
                ('quantity', models.IntegerField(help_text='Number of items taken or returned')),
                ('notes', models.TextField(blank=True, help_text='Additional context or details about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this transaction occurred')),
                ('stock_before', models.IntegerField(help_text='Stock quantity before this transaction')),
                ('stock_after', models.IntegerField(help_text='Stock quantity after this transaction')),
                ('created_by', models.ForeignKey(help_text='User who performed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(blank=True, help_text='Reason for transaction (from standardized list)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.takereason')),
                ('variant', models.ForeignKey(help_text='Specific size/color variant that was taken or returned', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apparel.apparelvariant')),
            ],
            options={
                'verbose_name': 'Apparel Transaction',
                'verbose_name_plural': 'Apparel Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
