# Generated by Django 6.0 on 2026-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparelproduct',
            name='manufacturer_product_id',
            field=models.CharField(blank=True, help_text="Supplier's non-standardised product code", max_length=100),
        ),
        migrations.AddField(
            model_name='apparelproduct',
            name='merchant_product_id',
            field=models.CharField(blank=True, help_text='Your unique product code / SKU for customs declarations', max_length=100),
        ),
        migrations.AddField(
            model_name='apparelproduct',
            name='standardised_product_id',
            field=models.CharField(blank=True, help_text='Standardised code if exists: GTIN, EAN, ISBN. Enter NO if not applicable.', max_length=100),
        ),
        migrations.AddField(
            model_name='apparelproduct',
            name='supplier_phone',
            field=models.CharField(blank=True, help_text='Supplier contact phone number', max_length=50),
        ),
    ]
