# Generated by Django 6.0 on 2026-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0002_apparelproduct_manufacturer_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparelproduct',
            name='supplier_address',
            field=models.TextField(blank=True, help_text='Supplier mailing address'),
        ),
        migrations.AddField(
            model_name='apparelproduct',
            name='supplier_email',
            field=models.EmailField(blank=True, help_text='Supplier contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='apparelproduct',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier company or contact name', max_length=200),
        ),
    ]
