# Generated by Django 6.0 on 2026-06-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0003_apparelproduct_supplier_address_and_more'),
        ('core', '0003_stockadjustmentreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareltransaction',
            name='reason',
            field=models.ForeignKey(blank=True, help_text='Reason for transaction (from standardized list)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stockadjustmentreason'),
        ),
    ]
