# Generated by Django 6.0 on 2026-04-23 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_preparation', 'In Preparation'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current stage of the request workflow', max_length=20)),
                ('date_needed', models.DateField(help_text='Date by which items must be ready for collection')),
                ('notes', models.TextField(blank=True, help_text='Additional context or instructions from the requester')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from the preparation team (not visible to requester)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department for budget tracking purposes', on_delete=django.db.models.deletion.PROTECT, related_name='item_requests', to='core.department')),
                ('reason', models.ForeignKey(help_text='Reason for this request (from standardised list)', on_delete=django.db.models.deletion.PROTECT, related_name='item_requests', to='core.takereason')),
                ('requested_by', models.ForeignKey(help_text='Staff member who submitted this request', on_delete=django.db.models.deletion.PROTECT, related_name='item_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last person to modify this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Request',
                'verbose_name_plural': 'Item Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('gift', 'Gift'), ('apparel', 'Apparel Variant'), ('executive', 'Executive Office Item'), ('it', 'IT Asset'), ('office', 'Office & Events Item')], help_text='Which inventory category this item comes from', max_length=20)),
                ('item_id', models.PositiveIntegerField(help_text='Primary key of the item in its respective inventory model')),
                ('quantity_requested', models.PositiveIntegerField(help_text='Quantity originally requested by the staff member')),
                ('quantity_confirmed', models.PositiveIntegerField(blank=True, help_text='Quantity confirmed by preparation team (may differ from requested)', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price captured at time of request for budget calculations', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Item-specific notes or special instructions')),
                ('request', models.ForeignKey(help_text='The parent request this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item_requests.itemrequest')),
            ],
            options={
                'verbose_name': 'Item Request Line',
                'verbose_name_plural': 'Item Request Lines',
            },
        ),
    ]
