# Generated by Django 6.0 on 2026-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequestitem',
            name='item_type',
            field=models.CharField(choices=[('gift', 'Gift'), ('apparel', 'Apparel Variant'), ('executive', 'Executive Office Item'), ('it', 'IT Asset'), ('office', 'Office & Events Item'), ('miscellaneous', 'Miscellaneous Item')], help_text='Which inventory category this item comes from', max_length=20),
        ),
    ]
