# Generated by Django 6.0 on 2026-04-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Reason for manual stock adjustment (e.g. 'Restock', 'Return from Event')", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Adjustment Reason',
                'verbose_name_plural': 'Stock Adjustment Reasons',
                'ordering': ['name'],
            },
        ),
    ]
