# Generated by Django 6.0 on 2026-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stockadjustmentreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentreason',
            name='applies_to',
            field=models.CharField(choices=[('add', 'Add'), ('take', 'Take')], default='add', help_text='Which stock direction this reason appears for: adding stock or taking stock', max_length=10),
        ),
    ]
